"""
Django settings for chrisdjango project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&&&ru#@4=zy1r-u4saoejnapc%b()vag&=*-bh8sfc17u!u8r&'
#SECRET_KEY = os.environ['SECRET_KEY']
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
#DEBUG = False

#ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'siteapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware', #20190509
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chrisdjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
		'DIRS': [os.path.join(BASE_DIR+"/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'django.template.context_processors.static',#,'django.contrib.staticfiles'
            ],
        },
    },
]

WSGI_APPLICATION = 'chrisdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': { 
	#'mssql': { 
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
				},	
	'mssql': {
	            'ENGINE': 'sql_server.pyodbc',
                'NAME':'erps',
                'HOST':'192.168.0.214',
                'USER':'apuser',
                'PASSWORD':'0920799339',
				'PORT': '1433',
	            'OPTIONS':{
                           'driver': 'ODBC Driver 11 for SQL Server',
                },
	 'oracle': {
                 'ENGINE': 'django.db.backends.oracle',
                 'NAME': 'E910',
                 'USER': 'PRODDTA',
                 'PASSWORD': 'E910Jde',
                 'HOST': "192.168.0.230",  # Set to empty string for localhost
                 'PORT': '1521',             #端口
 }			
	}	
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_URL = '/MEDIA/'
MEDIA_ROOT = 'MEDIA' ## 新增行
MEDIAFILES_DIR = os.path.join(BASE_DIR, 'MEDIA').replace("\\", "/")
#MEDIA_ROOT = os.path.join(BASE_DIR, 'MEDIA').replace("\\", "/")
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static' ## 新增行
STATICFILES_DIR = os.path.join(BASE_DIR, 'static').replace("\\", "/")  
#STATICFILES_FINDERS = ("django.contrib.staticfiles.finders.FileSystemFinder","django.contrib.staticfiles.finders.AppDirectoriesFinder")
#STATIC_ROOT = os.path.join(os.path.dirname(__file__),'static')
#STATIC_ROOT = os.path.join(BASE_DIR,'static')
#STATICFILES_DIRS = (('images',os.path.join(STATIC_ROOT,'images').replace('\\','/') ),)
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]
DEBUG = False
TEMPLATE_DEBUG = True
#ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['*']
